# node3 configuration
host: "127.0.0.1"
port: 4224

# Cluster configuration
cluster {
    name: nats-cluster
    port: 6224
    routes: [
    "nats://127.0.0.1:6222",
    "nats://127.0.0.1:6223",
    "nats://127.0.0.1:6224"
    ]
}

# Logging
log_file: "/Users/tomshine/code/github-shine/experiments/nats-server/nats-cluster/node3/nats-server.log"
debug: false
trace: false

# Optional: Monitoring
http_port: 8224
